---
- name: add epel repo
  yum:
    name: "{{ common_redhat_epel_rpm }}"

- name: perform a yum update
  yum:
    name: '*'
    state: latest
  when: common_upgrade_base | bool

- name: install baseline dependencies
  yum:
    name: "{{ item }}"
  with_items: "{{ common_rpms }}"

- name: install extra rpms
  yum:
    name: "{{ item }}"
  with_items: "{{ common_extra_rpms }}"
