---
kubernetes_master_kubeadm_config:
  kubernetesVersion: 1.11.3
  api:
    advertiseAddress: "{{ kubernetes_common_api_ip }}"
  apiServerExtraArgs:
    "endpoint-reconciler-type": "lease"
  apiServerCertSANs:
  - "{{ kubernetes_common_api_fqdn }}"
  - "{{ kubernetes_common_api_ip }}"
  etcd:
    endpoints: "{{ etcd_client_endpoints }}"
  token: "{{ generated_token.stdout }}"
