---
- name: add the kubernetes apt repo key
  apt_key:
    url: "{{ kubernetes.apt_key_url }}"
    state: present

- name: add the kubernetes apt repo
  apt_repository:
    repo: "{{ kubernetes.apt_repo_string }}"
    update_cache: True
    state: present

- name: install kubernetes packages
  apt:
    name: "{{ item }}"
  with_items:
    - "kubelet={{ kubernetes.version|kube_platform_version('debian') }}"
    - "kubeadm={{ kubernetes.version|kube_platform_version('debian') }}"
    - "kubectl={{ kubernetes.version|kube_platform_version('debian') }}"
    - "kubernetes-cni={{kubernetes.cni_version|kube_platform_version('debian') }}"
