---
- name: add the kubernetes yum repo key
  yum_repository:
    name: kubernetes
    description: the kubernetes yum repo
    baseurl: "{{ kubernetes.yum_baseurl }}"
    gpgcheck: True
    gpgkey: "{{ kubernetes.yum_gpgkey }}"

- name: install the kubernetes yum packages
  yum:
    name: "{{ item }}"
    allow_downgrade: True
  with_items:
    - "kubelet-{{ kubernetes.version|kube_platform_version('redhat') }}"
    - "kubeadm-{{ kubernetes.version|kube_platform_version('redhat') }}"
    - "kubectl-{{ kubernetes.version|kube_platform_version('redhat') }}"
    - "kubernetes-cni-{{kubernetes.cni_version|kube_platform_version('redhat')}}"
