---
- name: update /etc/hosts to include cluster fqdn
  lineinfile:
    dest: /etc/hosts
    line: "{{ kubernetes_common_api_ip }} {{ kubernetes_common_api_fqdn }}"
    state: present
  when: kubernetes_common_api_ip is defined and kubernetes_common_api_fqdn is defined

- name: determine whether kubeadm needs to be run
  stat:
    path: /etc/kubernetes/manifests/kube-apiserver.yaml
  register: kubeadm_apiserver_manifest

- name: generate a kubeadm token
  command: "/usr/bin/kubeadm token generate"
  register: generated_token
  run_once: True
  delegate_to: "{{ groups['primary_master']|first }}"

- include_tasks: install.yml
  when: wardroom_action == 'install'

- include_tasks: upgrade.yml
  when: wardroom_action == 'upgrade'
